* `pandasql` allows to query pandas DataFrame using SQL syntax.

In [6]:
import pandas as pd
import pandasql as psql

In [7]:
df = pd.read_csv('data/aadhaar_data.csv')

In [8]:
df.head()

,Registrar,Enrolment Agency,State,District,Sub District,Pin Code,Gender,Age,Aadhaar generated,Enrolment Rejected,Residents providing email,Residents providing mobile number
0,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Namkum,834003,M,63,0,1,0,1
1,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Ranchi,834004,F,36,0,1,0,1
2,Allahabad Bank,Vakrangee Softwares Limited,Gujarat,Surat,Nizar,394380,M,10,1,0,0,0
3,Allahabad Bank,Vakrangee Softwares Limited,Himachal Pradesh,Kangra,Baijnath,176081,M,44,1,0,1,1
4,Allahabad Bank,Vakrangee Softwares Limited,Madhya Pradesh,Chhindwara,Pandhurna,480334,M,35,1,0,0,0

In [9]:
df.rename(columns= lambda x: x.replace(' ', '_').lower(), inplace = True)

In [11]:
df.shape

(119998, 12)

* Let's choose first 20 rows and few columns from dataframe using pandasql

In [12]:
q = 'SELECT Registrar, Enrolment_Agency FROM df LIMIT 20;'

In [14]:
psql.sqldf(q, locals())  # locals() and globals() showing session/env variables

         registrar             enrolment_agency
0   Allahabad Bank            Tera Software Ltd
1   Allahabad Bank            Tera Software Ltd
2   Allahabad Bank  Vakrangee Softwares Limited
3   Allahabad Bank  Vakrangee Softwares Limited
4   Allahabad Bank  Vakrangee Softwares Limited
5   Allahabad Bank  Vakrangee Softwares Limited
6   Allahabad Bank  Vakrangee Softwares Limited
7   Allahabad Bank  Vakrangee Softwares Limited
8   Allahabad Bank  Vakrangee Softwares Limited
9   Allahabad Bank  Vakrangee Softwares Limited
10  Allahabad Bank  Vakrangee Softwares Limited
11  Allahabad Bank  Vakrangee Softwares Limited
12  Allahabad Bank  Vakrangee Softwares Limited
13  Allahabad Bank  Vakrangee Softwares Limited
14  Allahabad Bank  Vakrangee Softwares Limited
15  Allahabad Bank  Vakrangee Softwares Limited
16  Allahabad Bank  Vakrangee Softwares Limited
17  Allahabad Bank  Vakrangee Softwares Limited
18  Allahabad Bank  Vakrangee Softwares Limited
19  Allahabad Bank  Vakrangee Softwares Limited

In [15]:
q = "SELECT * FROM df WHERE state='Gujarat';"

In [16]:
psql.sqldf(q, locals())

,registrar,enrolment_agency,state,district,sub_district,pin_code,gender,age,aadhaar_generated,enrolment_rejected,residents_providing_email,residents_providing_mobile_number
0,Allahabad Bank,Vakrangee Softwares Limited,Gujarat,Surat,Nizar,394380,M,10,1,0,0,0
1,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Ahmedabad,Ahmadabad City,380050,F,61,1,0,0,1
2,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Amreli,Rajula,365560,F,34,1,0,0,1
3,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Amreli,Rajula,365560,M,38,1,0,0,1
4,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Junagadh,Patan Veraval,362268,F,35,1,0,0,1
5,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Kachchh,Rapar,370145,M,9,1,0,0,1
6,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Kachchh,Rapar,370165,M,20,1,0,0,1
7,Bank Of India,Frontech Systems Pvt Ltd,Gujarat,Junagadh,Kodinar,362720,M,25,1,0,0,1
8,Bank Of India,Frontech Systems Pvt Ltd,Gujarat,Surendra Nagar,Sayla,363430,F,27,1,0,0,1
9,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Ahmadabad City,380004,M,7,1,0,0,1
10,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Ahmadabad City,380061,F,23,0,1,0,1
11,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Daskroi,380059,M,48,1,0,0,0
12,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Amreli,Amreli,365601,F,44,1,0,0,1
13,Bank Of India,Matrix Processing House,Gujarat,Ahmedabad,Ahmadabad City,382475,M,45,1,0,0,1
14,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361001,F,26,1,0,0,1
15,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361130,F,26,1,0,0,1
16,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361130,M,29,1,0,0,1
17,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jamjodhpur,360515,F,26,1,0,0,1
18,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,F,5,1,0,0,0
19,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,F,27,1,0,0,1
20,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,M,29,1,0,0,1
21,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Kalyanpur,361320,M,21,1,0,0,1
22,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mandvi,370455,M,20,1,0,0,1
23,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mundra,370410,M,6,1,0,0,1
24,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mundra,370410,M,34,1,0,0,1
25,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Morvi,363642,F,26,1,0,0,1
26,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Morvi,363642,M,33,1,0,0,1
27,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Paddhari,360110,M,31,1,0,0,1
28,Bank Of India,Matrix Processing House,Gujarat,Surendra Nagar,Chotila,363520,M,29,1,0,0,1
29,Bank Of India,Matrix Processing House,Gujarat,Surendra Nagar,Limbdi,363421,F,32,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
55,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,20,0,1,0,1
56,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,23,1,0,0,1
57,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,26,1,0,0,1
58,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,31,1,0,0,1
59,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,35,1,0,0,1
60,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,8,1,0,0,1
61,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,11,1,0,0,1
62,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,50,1,0,0,1
63,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,F,37,1,0,0,1
64,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,11,1,0,0,1
65,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,16,1,0,0,1
66,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,21,1,0,0,0
67,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,27,1,0,0,1
68,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Umbergaon,396155,F,31,1,0,0,1
69,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Banaskantha,Danta,385120,F,25,1,0,0,1
70,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Valsad,Pardi,396191,M,56,1,0,0,1
71,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Valsad,Pardi,396191,M,62,1,0,0,1
72,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Ahmedabad,Ahmadabad City,380016,M,29,1,0,0,1
73,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Bharuch,Anklesvar,392011,M,59,1,0,0,1
74,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Vadodara,Padra,390016,M,29,1,0,0,1
75,CSC e-Governance Services India Limited,CMS Computers Ltd,Gujarat,Valsad,Pardi,396195,M,22,1,0,0,1
76,CSC e-Governance Services India Limited,Vakrangee Softwares Limited,Gujarat,Ahmedabad,Ahmadabad City,380015,F,50,1,0,0,1
77,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,F,9,1,0,0,1
78,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,F,36,1,0,0,1
79,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,M,12,1,0,0,1
80,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Palanpur,385001,F,8,1,0,0,1
81,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Palanpur,385001,F,13,1,0,0,1
82,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Vadgam,385210,M,30,1,0,0,1
83,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Kachchh,Rapar,370165,M,26,1,0,0,1
84,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Patan,Sidhpur,384151,F,12,1,0,0,1

In [17]:
q = 'SELECT district, sum(aadhaar_generated) FROM df GROUP BY district'

In [18]:
psql.sqldf(q, locals())

            district  sum(aadhaar_generated)
0           Adilabad                       1
1               Agra                       9
2         Ahmadnagar                     552
3        Ahmed Nagar                       0
4          Ahmedabad                       9
5              Ajmer                     527
6              Akola                      55
7          Alappuzha                       1
8            Aligarh                       7
9          Alirajpur                    2965
10         Allahabad                     137
11            Almora                       8
12             Alwar                     303
13            Ambala                      70
14    Ambedkar Nagar                      13
15            Amethi                       1
16          Amravati                      11
17            Amreli                       4
18          Amritsar                     269
19            Amroha                       7
20        Ananthapur                       5
21             Angul                       5
22           Anuppur                    1938
23            Araria                       3
24             Arwal                       6
25       Ashok Nagar                      72
26           Auraiya                      10
27        Aurangabad                     533
28          Azamgarh                      16
29          Bagalkot                      33
..               ...                     ...
498           Ujjain                     913
499           Umaria                    1992
500              Una                      56
501          Unakoti                       6
502            Unnao                       2
503   Uttar Dinajpur                       2
504   Uttara Kannada                      10
505         Vadodara                       4
506         Vaishali                      16
507           Valsad                      30
508         Varanasi                      13
509          Vellore                       8
510          Vidisha                     887
511       Viluppuram                      85
512     Virudhunagar                       5
513    Visakhapatnam                       6
514     Vizianagaram                       5
515         Warangal                       4
516           Wardha                       8
517           Washim                     282
518   West Champaran                       9
519       West Delhi                     157
520  West Garo Hills                       1
521    West Godavari                       4
522       West Siang                       1
523   West Singhbhum                    4170
524     West Tripura                     392
525           Yadgir                      69
526     Yamuna Nagar                    1586
527         Yavatmal                     469

[528 rows x 2 columns]

In [19]:
q = 'SELECT district, sub_district, sum(aadhaar_generated) FROM df GROUP BY district, sub_district'

In [20]:
psql.sqldf(q, locals())

            district          sub_district  sum(aadhaar_generated)
0           Adilabad            Lokeswaram                       1
1               Agra                   Bah                       3
2               Agra              Etmadpur                       1
3               Agra             Fatehabad                       1
4               Agra             Kheragarh                       2
5               Agra               Kiraoli                       2
6         Ahmadnagar                 Akola                       3
7         Ahmadnagar               Jamkhed                       2
8         Ahmadnagar                Karjat                       3
9         Ahmadnagar             Kopargaon                       4
10        Ahmadnagar                 Nagar                       4
11        Ahmadnagar                Nevasa                     139
12        Ahmadnagar                Parner                       5
13        Ahmadnagar              Pathardi                     114
14        Ahmadnagar                 Rahta                       1
15        Ahmadnagar                Rahuri                     123
16        Ahmadnagar             Sangamner                       2
17        Ahmadnagar              Shevgaon                     120
18        Ahmadnagar             Shrigonda                      32
19       Ahmed Nagar                Karjat                       0
20       Ahmed Nagar             Kopargaon                       0
21       Ahmed Nagar                 Nagar                       0
22       Ahmed Nagar              Pathardi                       0
23       Ahmed Nagar                 Rahta                       0
24       Ahmed Nagar                Rahuri                       0
25         Ahmedabad        Ahmadabad City                       8
26         Ahmedabad               Daskroi                       1
27             Ajmer                 Ajmer                       1
28             Ajmer                Beawar                      29
29             Ajmer                Bhinay                      19
...              ...                   ...                     ...
2440  West Singhbhum              Majhgaon                     289
2441  West Singhbhum              Manjhari                       1
2442  West Singhbhum            Manoharpur                     227
2443  West Singhbhum  Noamundi (barajamda)                     827
2444  West Singhbhum                 Sonua                     109
2445  West Singhbhum             Tantnagar                       7
2446  West Singhbhum                 Tonto                     406
2447    West Tripura        Agartala Sadar                     112
2448    West Tripura                 Dukli                      24
2449    West Tripura              Hezamara                      42
2450    West Tripura               Jirania                     101
2451    West Tripura                Mandai                      44
2452    West Tripura              Mohanpur                      69
2453          Yadgir               Shahpur                      42
2454          Yadgir              Shorapur                      25
2455          Yadgir                Yadgir                       2
2456    Yamuna Nagar          Chhachhrauli                     148
2457    Yamuna Nagar              Jagadhri                    1438
2458        Yavatmal                  Arni                      13
2459        Yavatmal             Babulgaon                      49
2460        Yavatmal                Digras                       4
2461        Yavatmal              Ghatanji                      43
2462        Yavatmal                Kalamb                     189
2463        Yavatmal               Kelapur                       9
2464        Yavatmal              Mahagaon                      36
2465        Yavatmal                 Pusad                      33
2466        Yavatmal              Ralegaon                      24
2467        Yavatmal              Umarkhed                      34
2468        Yavatmal              Yavatmal                      34
2469        Yavatmal           Zari-Jamani                       1

[2470 rows x 3 columns]

In [21]:
q = 'SELECT district, sub_district, sum(aadhaar_generated) FROM df WHERE age > 60 GROUP BY district, sub_district'

In [22]:
psql.sqldf(q, locals())

           district          sub_district  sum(aadhaar_generated)
0        Ahmadnagar                 Nagar                       0
1        Ahmadnagar                Nevasa                      18
2        Ahmadnagar                Parner                       1
3        Ahmadnagar              Pathardi                      13
4        Ahmadnagar                 Rahta                       0
5        Ahmadnagar                Rahuri                       5
6        Ahmadnagar              Shevgaon                      23
7        Ahmadnagar             Shrigonda                       3
8       Ahmed Nagar             Kopargaon                       0
9       Ahmed Nagar                 Nagar                       0
10        Ahmedabad        Ahmadabad City                       1
11            Ajmer                Beawar                       3
12            Ajmer                Bhinay                       1
13            Ajmer                 Kekri                      17
14            Ajmer            Kishangarh                       3
15            Ajmer             Peesangan                       1
16            Ajmer                Sarwar                      16
17            Akola               Balapur                       2
18            Akola               Telhara                       1
19        Alirajpur                Bhavra                      32
20        Alirajpur                 Jobat                      16
21        Allahabad             Allahabad                       9
22        Allahabad                  Bara                       1
23        Allahabad                Koraon                       1
24            Alwar                 Alwar                       1
25            Alwar                Behror                       5
26            Alwar              Kathumar                       1
27            Alwar        Kishangarh Bas                       6
28            Alwar              Kotkasim                       1
29            Alwar               Rajgarh                       0
..              ...                   ...                     ...
879  West Singhbhum         Chakradharpur                      15
880  West Singhbhum              Goilkera                       8
881  West Singhbhum          Jagannathpur                      26
882  West Singhbhum             Jhinkpani                       2
883  West Singhbhum             Khuntpani                      13
884  West Singhbhum            Kumardungi                      14
885  West Singhbhum              Majhgaon                      12
886  West Singhbhum            Manoharpur                       9
887  West Singhbhum  Noamundi (barajamda)                      37
888  West Singhbhum                 Sonua                      10
889  West Singhbhum             Tantnagar                       0
890  West Singhbhum                 Tonto                      16
891    West Tripura        Agartala Sadar                       6
892    West Tripura                 Dukli                       1
893    West Tripura              Hezamara                       2
894    West Tripura               Jirania                       6
895    West Tripura              Mohanpur                       2
896          Yadgir               Shahpur                       9
897    Yamuna Nagar          Chhachhrauli                      12
898    Yamuna Nagar              Jagadhri                     131
899        Yavatmal                  Arni                       2
900        Yavatmal             Babulgaon                      11
901        Yavatmal                Digras                       0
902        Yavatmal              Ghatanji                       3
903        Yavatmal                Kalamb                      24
904        Yavatmal              Mahagaon                       5
905        Yavatmal                 Pusad                       2
906        Yavatmal              Ralegaon                       1
907        Yavatmal              Umarkhed                       6
908        Yavatmal              Yavatmal                       3

[909 rows x 3 columns]